ENABLED: true
SETTINGS:
  PLAYERS-IN-RTP: 150
  MAX-ATTEMPTS: 5

MESSAGES:
  DISABLED: "&cRTP is currently disabled."
  COOLDOWN: "&cYou can't rtp for another {remaining}s."
  MAX-PLAYERS: "&cToo many players are using RTP right now. Please try again later."
  WORLD-NOT-EXIST: "&cThe world does not exist."
  SEARCHING: "&dSearching for a safe location..."
  SAFE-LOCATION-FOUND: ""
  MAX-ATTEMPTS: "&cCould not find a safe location after {attempts} attempts."
  DESTINATION-DISABLED: "&cThis RTP destination is currently disabled."
  UNSAFE-LOCATION: "&cThe location is unsafe"

DENIED-WORLDS:
  - afk

WORLD-SETTINGS:
  world:
    MAX-RADIUS: 20000
    MIN-RADIUS: 10000
    CENTER-X: 0
    CENTER-Z: 0
    COOLDOWN: 0
  world_nether:
    MAX-RADIUS: 7500
    MIN-RADIUS: 5000
    CENTER-X: 0
    CENTER-Z: 0
    COOLDOWN: 0
  world_the_end:
    MAX-RADIUS: 10000
    MIN-RADIUS: 7000
    CENTER-X: 0
    CENTER-Z: 0
    COOLDOWN: 0

RTP-MENU:
  TITLE: "&8\u0280\u1D00\u0274\u1D05\u1D0F\u1D0D \u1D1B\u1D07\u029F\u1D07\u1D18\u1D0F\u0280\u1D1B"
  SIZE: 27
  PLACEHOLDER: true
  BUTTONS:
    OVERWORLD:
      DISPLAY-NAME: "&#0bee88\u1D0F\u1D20\u1D07\u0280\u1D21\u1D0F\u0280\u029F\u1D05"
      MATERIAL: "GRASS_BLOCK"
      SLOT: 11
      WORLD: "world"
      ENABLED: true
      LORE:
        - "&fClick to randomly teleport"
        - ""
        - "&7Players: &b{players}"
        - "&7Ping: &b{ping}ms"
    NETHER:
      DISPLAY-NAME: "&#0bee88\u0274\u1D07\u1D1B\u029C\u1D07\u0280"
      MATERIAL: "NETHERRACK"
      SLOT: 13
      WORLD: "world_nether"
      ENABLED: true
      LORE:
        - "&fClick to randomly teleport"
        - ""
        - "&7Players: &b{players}"
        - "&7Ping: &b{ping}ms"
    THE_END:
      DISPLAY-NAME: "&#0bee88\u1D07\u0274\u1D05"
      MATERIAL: "END_STONE"
      SLOT: 15
      WORLD: "world_the_end"
      ENABLED: true
      LORE:
        - "&fClick to randomly teleport"
        - ""
        - "&7Players: &b{players}"
        - "&7Ping: &b{ping}ms"
